<a href="https://colab.research.google.com/github/lazizrakhmat/DS-Pandas/blob/main/_2_2_8_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ma'lumotlar tahlili. Pandas kutubxonasi.
##2.2.8 Foydali funksiyalar
###ARIFMETIK AMALLAR

In [1]:
import pandas as pd
import numpy as np

Pandas Obyeki elementlariga Funksiyalar qo'llash

In [3]:
df = pd.DataFrame(np.random.randn(3, 4), index=list('abc'), columns=['Olma', 'Anor', 'Qovun', 'Anjir'])
df

       Olma      Anor     Qovun     Anjir
a  0.201041  0.366123 -2.329657 -0.290734
b  1.235619 -0.726231 -0.653937 -1.649183
c  0.858494 -0.507680 -0.195748  0.737669

In [4]:
np.abs(df) # .abs() - bu function bizga manfiy bo'lsaham musbas qiymat qaytaradi

       Olma      Anor     Qovun     Anjir
a  0.201041  0.366123  2.329657  0.290734
b  1.235619  0.726231  0.653937  1.649183
c  0.858494  0.507680  0.195748  0.737669

In [5]:
np.round(df) # .round() - bu function bizga butun qiymat qaytaradi

   Olma  Anor  Qovun  Anjir
a   0.0   0.0   -2.0   -0.0
b   1.0  -1.0   -1.0   -2.0
c   1.0  -1.0   -0.0    1.0

In [6]:
df

       Olma      Anor     Qovun     Anjir
a  0.201041  0.366123 -2.329657 -0.290734
b  1.235619 -0.726231 -0.653937 -1.649183
c  0.858494 -0.507680 -0.195748  0.737669

In [7]:
df.mean() # .mean() bu function bizga o'rtacha qiymatni qaytaradi, ustunlari bo'yicha

Olma     0.765051
Anor    -0.289263
Qovun   -1.059781
Anjir   -0.400749
dtype: float64

In [8]:
df.mean(axis=1) # .mean(axis=1) bu esa qatorlari bo'yicha

a   -0.513307
b   -0.448433
c    0.223184
dtype: float64

In [9]:
df.apply(np.abs)

       Olma      Anor     Qovun     Anjir
a  0.201041  0.366123  2.329657  0.290734
b  1.235619  0.726231  0.653937  1.649183
c  0.858494  0.507680  0.195748  0.737669

In [10]:
df.apply(sum, axis=1)

a   -2.053228
b   -1.793732
c    0.892735
dtype: float64

In [13]:
f = lambda x: x.max() - x.min() # lambda bizda bu yerda x.max() va x.min() qiymatlar o'rtachasini topib berdi

In [15]:
df.apply(f)

Olma     1.034578
Anor     1.092354
Qovun    2.133909
Anjir    2.386852
dtype: float64